#include <iostream>
#include <string>
#include <sstream>

using namespace std;

/*
Gabe is practicing for a contest where he must recite the alphabet backwards as fast as possible from a given starting 
letter. Because he is bad with the alphabet, every time he moves backwards one letter, 
he must recite the entire alphabet song up to the next letter he says. For example, if Gabe wants to recite backwards 
from "e", he will first say "e", then "a, b, c, d", then "a, b, c", then "a, b", and finally "a". 
This will result in a final string S of: "e, a, b, c, d, a, b, c, a, b, a".

He wants you to watch him practice and tell him how helpful it would be to memorize a specific section. 
In order to do this, you must find how many times a certain substring of the final string S appears in the total string. 
For example, he could ask you how many times he says "a, b, c" in the above example, and you would reply: twice, 
once when singing the song up to "d", and another time when singing up to "c".
It is guaranteed that the string of letters will appear at least once in the total string S.

💡 Hint: you do not need to construct the total string S in order to solve the problem. 
It is possible to solve in linear time (with respect to the length of the string of letters), 
and constant auxiliary space (even if the alphabet had any number of letters).

📃 Input Format
[starting lowercase latin letter] [search string of lowercase latin letters]

📝 Output Format
[a single number; the number of times that search string appears in the string generated by the above procedure]
*/
void charProblem(char start, string phrase){
    char max;
    for(char c : phrase){
        if(c<= max){cout << 1 << endl; return;}
        max = c;
    }
    cout << int(start - max) << endl;
}
void intProblem(int start, int length){
    int num;
    int max = -1;
    for(int i = 0; i < length; i++){
        cin >> num;
        if(num <= max){cout << 1 << endl; return;}
        max = num;
    }
    cout << start - max << endl;
}

int main(){
    char c;
    cin >> c;
    if('a' <= c && c <= 'z'){
        string phrase;
        getline(cin, phrase);
        charProblem(c, phrase.substr(1));
        return 0;
    }
    if('0' <= c && c <= '9'){
        string line;
        getline(cin, line);
        stringstream ss;
        ss << c << line;

        int start, length;
        ss >> start >> length;
        intProblem(start, length);
        return 0;
    }
    return -1;
}